Inventorystat
PurdueSIGGD/Lumina pull request #8
Opened 2017-03-28 22:43 UTC by EverettG

Please Please Please I need it soo bad ooh ....ooh...OOOH MUH LIGHTFORCE

2017-03-29 00:20 UTC, Lonswaya commented on Assets/C#/Hittable.cs
> +	public enum DamageType { Neutral, Fire, Ice, Electric, Denim, Umbra };
> Denim

Yes

2017-03-29 00:30 UTC, Lonswaya requested changes

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/Inventory.cs
> +﻿using System.Collections;
What was the reason for this again?

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/InventoryController.cs
> +			case Weapon.WeaponCategory.Melee:
We'll have to change these later in the weapons branch @AndrewGraber

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/InventoryController.cs
> +			case Weapon.WeaponCategory.Melee:
That is, if you renamed those

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/InventoryController.cs
> +		switch (p.itemType) {
Didn't we also want to use this for light force as well?

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/StatsController.cs
> +	public void UpgradeMaxLightt(){
Lightt typo

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/StatsController.cs
> +	public float UpdateLightt(float amount) {
Lightt typo

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/StatsController.cs
> +	public float ApplyDamageTypeHitMod(float damage, DamageType type) {
These should be private

2017-03-29 00:30 UTC, Lonswaya commented on Assets/C#/StatsController.cs
> +	public float ApplyArmorHitMod(float damage, DamageType type) {
These should be private

2017-03-29 00:32 UTC, Lonswaya commented
Also, please pull from master and fix those conflicts

2017-03-29 00:34 UTC, AndrewGraber commented on Assets/C#/Inventory.cs
> +﻿using System.Collections;
Oh that was me. At one point I was using something from it, then it got deleted

2017-03-30 22:51 UTC, Lonswaya approved these changes

2017-03-30 22:55 UTC, AndrewGraber approved these changes
:)

2017-03-30 22:56 UTC, merged